package solver;

import java.util.ArrayList;
import java.util.Objects;

// State represents the positions of all the crates and position of the player which are always changing
public class State {
    public ArrayList<Coordinate> cratePosList;
    public Board board;
    public Coordinate playerPos;

    // Key generated by the zobrist hash or the move function
    public long hashKey;

    public State(long key, Coordinate playerPos) {
        this.hashKey = key;
        this.playerPos = playerPos;
    }

    public State(ArrayList<Coordinate> cratePosList, Board board, Coordinate playerPos) {
        this.cratePosList = cratePosList;
        this.board = board;
        this.playerPos = playerPos;
    }

    // Returns a deep copy of State (actually just the itemData and cratePosList)
    public State copy() {
        State newState = new State(this.hashKey, this.playerPos);

        newState.cratePosList = new ArrayList<>();
        for (Coordinate pos : this.cratePosList)
            newState.cratePosList.add(new Coordinate(pos.x, pos.y));

        Board newBoard = new Board(this.board.mapData, this.board.width, this.board.height);
        newBoard.itemData = new char[newBoard.height][newBoard.width];
        for (int i = 0; i < newBoard.height; i++) {
            newBoard.itemData[i] = this.board.itemData[i].clone();
        }
        newState.board = newBoard;
        return newState;
    }

    public void print() {
        for (int i = 0; i < board.mapData.length; i++) {
            for (int j = 0; j < board.mapData[i].length; j++) {
              if (board.mapData[i][j] == BoardValues.WALL.value)
              System.out.print(board.mapData[i][j] + " ");
              else
              System.out.print(board.itemData[i][j] + " ");
            }
            System.out.println();
        }
    }

    // Used for hashing and PQs
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        State that = (State) o;

        return Objects.equals(this.cratePosList, that.cratePosList) &&
               Objects.equals(playerPos, that.playerPos);
    }

    @Override
    public int hashCode() {
        return Objects.hash(cratePosList, playerPos);
    }
}